### ISSUE TITLE
Error: parsing resolved p2p refs, expected properties not found

### ISSUE THREAD

**Issue by rkosafo** [ionide/dotnet-proj-info#12]
I get the error below when I try to compile a solution with two projects with a project reference.

	ERROR: parsing resolved p2p refs, expected properties not found '[|"ProjectReferenceFullPath=C:\Users\rkosa\OneDrive\Playground\s\Fable.Cai\Fable.Cai.fsproj;"|]'
	   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
	   at Dotnet.ProjInfo.Inspect.parseResolvedP2PRefOut[a](String outFile)
	   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x)
	   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
	   at Microsoft.FSharp.Core.ResultModule.Map[T,TResult,TError](FSharpFunc`2 mapping, FSharpResult`2 result)
	   at Fable.CLI.ProjectCoreCracker.projInfo(FSharpList`1 additionalMSBuildProps, String file)
	   at Fable.CLI.ProjectCracker.fullyCrackFsproj(String projFile)
	   at Fable.CLI.ProjectCracker.getProjectOptionsFromFsproj(Message msg, String projFile)
	   at Fable.CLI.ProjectCracker.retry@286(FSharpChecker checker, Message msg, String projFile, DateTime retryUntil, Unit unitVar0)
	   at Fable.CLI.ProjectCracker.retryGetProjectOpts(FSharpChecker checker, Message msg, String projFile)
	   at Fable.CLI.ProjectCracker.getFullProjectOpts(FSharpChecker checker, Message msg, String projFile)
	   at Fable.CLI.StateUtil.createProject(FSharpChecker checker, Boolean isWatchCompile, FSharpOption`1 prevProject, Message msg, String projFile)
	   at Fable.CLI.StateUtil.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg)
	   at Fable.CLI.StateUtil.loop@195-6.Invoke(Tuple`2 _arg1)

This is the sample project - [project.zip](https://github.com/enricosada/dotnet-proj-info/files/1457300/project.zip)

To reproduce,

    dotnet build
    cd Sky1099.Web
    yarn
    dotnet fable yarn-start

**Comment by amcguier** [comment]
I can replicate this error when trying to load the project in fsautocomplete on OSX. 

This repository reproduces the error for me. 
https://github.com/amcguier/project-reference-error

`dotnet build` on the command line completes cleanly but trying to parse the project with 
`mono fsautocomplete.exe` fails with the following error message 

    parsing resolved p2p refs, expected properties not found ’[|"ProjectReferenceFullPath=/Users/amcguier/Code/project-reference-error/src/myproject/myproject.fsproj;"|]’

I'm using fsharpautocomplete version `0.34.0` which corresponds to this version fsharp-mode for emacs https://github.com/fsharp/emacs-fsharp-mode/tree/1.9.11

**Comment by mavnn** [comment]
@amcguier do you know if this ever got fixed anywhere? I'm still hitting it on some projects (but not others) with emacs-fsharp-mode on OSX.

**Comment by mavnn** [comment]
Even if you've just found a work around, that would be really nice to know!

**Comment by mavnn** [comment]
@amcguier thanks! It looks like building the master branch of fsautocomplete is sufficient now. I might see what needs to be done to get a new release to elpa.

**Comment by paytonrules** [comment]
Just a follow up that I still have to build the master branch of fsautocomplete for this to work, even though the branch that ships with fsharp-mode reports it as the same as master.

**Comment by deapsquatter** [comment]
Copying all files from VSCode extension ionide.ionide-fsharp/bin to ~/.emacs.d/elpa/fsharp-mode-20180518.1120/bin fixed the issue for me.

**Comment by juergenhoetzel** [comment]
> @amcguier thanks! It looks like building the master branch of fsautocomplete is sufficient now. I might see what needs to be done to get a new release to elpa.

I can confirm that building `fsautocomplete.exe` from master fixes this issue for `fsharp-mode`:

It would be nice if someone makes a [new release 0.35](https://github.com/fsharp/FsAutoComplete/issues/291)
