### ISSUE TITLE
SDK 2.1.3 Preview 3 - msbuild failure when parsing SAFE client project

### ISSUE THREAD

**Issue by cartermp** [ionide/dotnet-proj-info#14]
Repro:

Ensure the following are installed:

* Master branch of [SAFE Bookstore](https://github.com/SAFE-Stack/SAFE-BookStore)
* [SDK 2.1.3 Preview3](https://dotnetcli.blob.core.windows.net/licavalc/Sdk/2.1.3-preview3-fnl-007228/dotnet-sdk-2.1.3-win-x64.exe)

Then run `build`.

Output:

```
Paket version 5.124.0
Downloading dotnet-fable 1.3.2
Downloading Fable.FCS 16.0.3
Downloading Fable.Elmish.Debugger 1.0.1
Downloading Fable.Import.Browser 0.1.2
Downloading Fable.Elmish 1.0.1
Downloading Fable.Compiler 1.3.2
Downloading Dotnet.ProjInfo 0.9
Downloading Fable.Core 1.3.1
Downloading Fable.PowerPack 1.3.1
Downloading Fable.React 1.2.2
Downloading Microsoft.NETCore.App 2.0.3
Downloading Microsoft.NETCore.DotNetHostPolicy 2.0.3
Downloading Microsoft.NETCore.DotNetHostResolver 2.0.3
Downloading Microsoft.NETCore.Platforms 2.0.1
Downloading Microsoft.NETCore.DotNetAppHost 2.0.3
Downloading System.Security.Cryptography.Algorithms 4.3.1
Downloading System.Security.Cryptography.X509Certificates 4.3.2
Downloading WindowsAzure.Storage 8.6
Downloading Mono.Cecil 0.10.0-beta7 (ServerTests)
Downloading canopy 1.6.1 (UITests)
Downloading Selenium.WebDriver 3.7 (UITests)
Performance:
 - Disk IO: 8 seconds
 - Average Download Time: 832 milliseconds
 - Number of downloads: 21
 - Average Request Time: 562 milliseconds
 - Number of Requests: 21
 - Runtime: 9 seconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
   <== BundleClient
      <== RunClientTests
         <== RenameDrivers
            <== BuildClientTests
               <== RunServerTests
                  <== BuildServerTests
                     <== BuildClient
                        <== BuildServer
                           <== SetReleaseNotes
                              <== InstallClient
                                 <== InstallDotNetCore
                                    <== Clean

The running order is:
  - Clean
  - InstallDotNetCore
  - InstallClient
  - SetReleaseNotes
  - BuildServer
  - BuildClient
  - BuildServerTests
  - RunServerTests
  - BuildClientTests
  - RenameDrivers
  - RunClientTests
  - BundleClient
  - All
Running build with 1 worker
Starting Target: Clean
Deleting contents of C:\repos\SAFE-BookStore\src\Client\bin
Deleting contents of C:\repos\SAFE-BookStore\src\Server\bin
Deleting contents of C:\repos\SAFE-BookStore\test\ServerTests\bin
Deleting contents of C:\repos\SAFE-BookStore\test\UITests\bin
Deleting contents of bin
Deleting contents of temp
Deleting contents of docs/output
Deleting contents of ./deploy
Deleting contents of C:\repos\SAFE-BookStore\src\Client\public/bundle
Finished Target: Clean
Starting Target: InstallDotNetCore (==> Clean)
dotnet --version
C:\Users\Phillip Carter\AppData\Local\dotnetcore\dotnet.exe --version
cmd 2.0.3 already installed in LocalApplicationData
Finished Target: InstallDotNetCore
Starting Target: InstallClient (==> InstallDotNetCore)
Node version:
C:\Program Files\nodejs\node.exe --version
v8.9.1
Yarn version:
C:\Program Files (x86)\Yarn\bin\yarn.cmd --version
1.3.2
C:\Program Files (x86)\Yarn\bin\yarn.cmd install --frozen-lockfile
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.24s.
Finished Target: InstallClient
Starting Target: SetReleaseNotes (==> InstallClient)
Finished Target: SetReleaseNotes
Starting Target: BuildServer (==> SetReleaseNotes)
C:\Users\Phillip Carter\AppData\Local\dotnetcore\dotnet.exe build
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Server -> C:\repos\SAFE-BookStore\src\Server\bin\Debug\netcoreapp2.0\Server.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.04
Finished Target: BuildServer
Starting Target: BuildClient (==> BuildServer)
C:\Users\Phillip Carter\AppData\Local\dotnetcore\dotnet.exe restore
  Restoring packages for C:\repos\SAFE-BookStore\src\Client\Client.fsproj...
  Restoring packages for C:\repos\SAFE-BookStore\src\Client\Client.fsproj...
  Restore completed in 197.7 ms for C:\repos\SAFE-BookStore\src\Client\Client.fsproj.
  Restore completed in 623.31 ms for C:\repos\SAFE-BookStore\src\Client\Client.fsproj.
C:\Users\Phillip Carter\AppData\Local\dotnetcore\dotnet.exe fable webpack -- -p
Fable (1.3.2) daemon started on port 61225
CWD: C:\repos\SAFE-BookStore\src\Client
cmd /C node "C:\repos\SAFE-BookStore\node_modules\webpack\bin\webpack.js" -p
Bundling for production...
ERROR: MSBuild failed with exitCode -2147450735 Working Directory: 'C:\repos\SAFE-BookStore\src\Client' Exe Path: 'dotnet' Args: 'msbuild C:\repos\SAFE-BookStore\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs "/p:_Inspect_FscArgs_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA729.tmp.FscArgs.txt" /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences "/p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72A.tmp.GetResolvedProjectReferences.txt" /t:_Inspect_GetProperties "/p:_Inspect_GetProperties_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72B.tmp.GetProperties.txt" /nologo /verbosity:quiet'
   at Fable.CLI.ProjectCoreCracker.projInfo(FSharpList`1 additionalMSBuildProps, String file)
   at Fable.CLI.ProjectCracker.fullyCrackFsproj(String projFile)
   at Fable.CLI.ProjectCracker.getProjectOptionsFromFsproj(Message msg, String projFile)
   at Fable.CLI.ProjectCracker.retry@275(FSharpChecker checker, Message msg, String projFile, DateTime retryUntil, Unit unitVar0)
   at Fable.CLI.ProjectCracker.retryGetProjectOpts(FSharpChecker checker, Message msg, String projFile)
   at Fable.CLI.ProjectCracker.getFullProjectOpts(FSharpChecker checker, Message msg, String projFile)
   at Fable.CLI.StateUtil.createProject(FSharpChecker checker, String[] dirtyFiles, FSharpOption`1 prevProject, Message msg, String projFile)
   at Fable.CLI.StateUtil.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg)
   at Fable.CLI.StateUtil.loop@228-6.Invoke(Tuple`2 _arg1)
Hash: fd4d9d487f7be4f2b287
Version: webpack 3.8.1
Time: 549ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.53 kB       0  [emitted]  main
bundle.js.map  6.88 kB       0  [emitted]  main
   [0] ./Client.fsproj 1.01 kB {0} [built] [failed] [1 error]

ERROR in ./Client.fsproj
Module build failed: Error: MSBuild failed with exitCode -2147450735 Working Directory: 'C:\repos\SAFE-BookStore\src\Client' Exe Path: 'dotnet' Args: 'msbuild C:\repos\SAFE-BookStore\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs "/p:_Inspect_FscArgs_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA729.tmp.FscArgs.txt" /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences "/p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72A.tmp.GetResolvedProjectReferences.txt" /t:_Inspect_GetProperties "/p:_Inspect_GetProperties_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72B.tmp.GetProperties.txt" /nologo /verbosity:quiet'
    at Loader.fableUtils.client.send.then.r (C:\repos\SAFE-BookStore\node_modules\fable-loader\index.js:67:22)
    at <anonymous>
Closing Fable daemon...
Running build failed.
Error:
System.Exception: dotnet fable webpack -- -p failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args)
   at FSI_0005.Build.clo@154-9.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0442948
InstallDotNetCore   00:00:00.2059501
InstallClient       00:00:04.9168186
SetReleaseNotes     00:00:00.0049815
BuildServer         00:00:07.8239116
BuildClient         Failure
Total:              00:00:16.3544592
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: dotnet fable webpack -- -p failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args)
   at FSI_0005.Build.clo@154-9.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

**Comment by Xiu-Li** [comment]
Tested on [**CLI/SDK: 2.1.3-preview3-fnl-007232** ](https://dotnetcli.blob.core.windows.net/licavalc/Sdk/2.1.3-preview3-fnl-007232/dotnet-sdk-2.1.3-win-x64.exe), and still repro.

**Comment by enricosada** [comment]
Can you try run the msbuild command shown in log, to see the real error?

in the log there is something like

```
Module build failed: Error: MSBuild failed with exitCode -2147450735 Working Directory: 'C:\repos\SAFE-BookStore\src\Client' Exe Path: 'dotnet' Args: 'msbuild C:\repos\SAFE-BookStore\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs "/p:_Inspect_FscArgs_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA729.tmp.FscArgs.txt" /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences "/p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72A.tmp.GetResolvedProjectReferences.txt" /t:_Inspect_GetProperties "/p:_Inspect_GetProperties_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72B.tmp.GetProperties.txt" /nologo /verbosity:quiet'
    at Loader.fableUtils.client.send.then.r (C:\repos\SAFE-BookStore\node_modules\fable-loader\index.js:67:22)
    at <anonymous>
```

so if you do 

```
dotnet msbuild C:\repos\SAFE-BookStore\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs "/p:_Inspect_FscArgs_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA729.tmp.FscArgs.txt" /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences "/p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72A.tmp.GetResolvedProjectReferences.txt" /t:_Inspect_GetProperties "/p:_Inspect_GetProperties_OutFile=C:\Users\Phillip Carter\AppData\Local\Temp\tmpA72B.tmp.GetProperties.txt" /nologo /verbosity:n
```

NOTE i have removed `/verbosity:quiet` at end, and added `/verbosity:n` , so is shown on console log too

meanwhile i'll send a PR to fable to show the msbuild log too in their log

**Comment by Xiu-Li** [comment]
After running the msbuild command:
`dotnet msbuild C:\Users\ddltd2\Downloads\SAFE-BookStore-master\src\Client\Client.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\ddltd2\AppData\Local\Temp\tmp2C55.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\ddltd2\AppData\Local\Temp\tmp2C56.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\ddltd2\AppData\Local\Temp\tmp2C57.tmp.GetProperties.txt /nologo /verbosity:n`

Show the following info:
`The specified SDK version [2.0.3] from global.json [C:\Users\ddltd2\Downloads\SAFE-BookStore-master\global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409`
![image](https://user-images.githubusercontent.com/24784908/33594803-58194740-d9d0-11e7-996a-487e0cdb903d.png)

**Comment by enricosada** [comment]
Ok now is easier to understand. thx a lot

Added https://github.com/fable-compiler/Fable/issues/1285 to improve the `dotnet fable` error message, so is not needed to manually rerun msbuild to see the real error

The  `global.json` specify to use 2.0.3. so dotnet.projinfo will use that, because invoke `dotnet` as shell. it atm ignore the real `dotnet` of `dotnet fable`.

@cartermp @Xiu-Li  as workaround for now, change the `global.json` value.

Long term, i need to think about how to find same parent `dotnet` host to use, the use used to run `dotnet fable`.
